apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: cqn4nilh7-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:7910f4a2c7de9fd9696a3b004bbd6c1fbf434884@sha256:e80d8778b0324f4652384be357308d855be6084e539b7a02ad3dd7a04fc0ce32
          name: container-image
